# Generated by Django 6.1.1 on 2026-10-06 20:29

from django.db import migrations, models

import robots.validators


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0002_alter_id_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="Optional note shown as a '# ...' line above this rule in robots.txt. robots.txt is public: do not put anything confidential here.",
                max_length=255,
                validators=[robots.validators.validate_single_line],
                verbose_name="comment",
            ),
        ),
    ]
