# Generated by Django 6.1.1 on 2026-10-06 21:54

from django.db import migrations, models

import robots.validators


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0003_rule_comment"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleanParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameters",
                    models.CharField(
                        help_text="Parameter names separated by &, e.g. ref&sid. Case-sensitive.",
                        max_length=255,
                        validators=[robots.validators.validate_clean_param_parameters],
                        verbose_name="parameters",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Optional path prefix, e.g. '/catalog/'. Leave empty to apply to the whole site.",
                        max_length=255,
                        validators=[robots.validators.validate_clean_param_path],
                        verbose_name="path",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(to="sites.site", verbose_name="sites"),
                ),
            ],
            options={
                "verbose_name": "Clean-param directive",
                "verbose_name_plural": "Clean-param directives",
            },
        ),
    ]
