# Generated by Django 6.1.1 on 2026-10-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0004_cleanparam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="disallowed",
            field=models.ManyToManyField(
                blank=True,
                help_text="The URLs which are not allowed to be accessed by bots. robots.txt is public and only asks well-behaved crawlers to stay away: it does not protect content, and listing a URL here makes it visible to everyone.",
                related_name="disallowed",
                to="robots.url",
                verbose_name="disallowed",
            ),
        ),
    ]
